# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Shane/Documents/Classes/ECE_385/Lab_7/lab_7_ash/lab_7.srcs/sources_1/bd/mb_block/ip/mb_block_i_hdmi_text_controller_0_0/mb_block_i_hdmi_text_controller_0_0.xci
# IP: The module: 'mb_block_i_hdmi_text_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Shane/Documents/Classes/ECE_385/Lab_7/lab_7_ash/lab_7.gen/sources_1/bd/mb_block_i/ip/edit_hdmi_text_controller_v1_0.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: c:/Users/Shane/Documents/Classes/ECE_385/Lab_7/lab_7_ash/lab_7.gen/sources_1/bd/mb_block_i/ip/edit_hdmi_text_controller_v1_0.srcs/sources_1/ip/hdmi_tx_0/hdmi_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# XDC: c:/Users/Shane/Documents/Classes/ECE_385/Lab_7/lab_7_ash/lab_7.gen/sources_1/bd/mb_block_i/ip/edit_hdmi_text_controller_v1_0.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Shane/Documents/Classes/ECE_385/Lab_7/lab_7_ash/lab_7.gen/sources_1/bd/mb_block_i/ip/edit_hdmi_text_controller_v1_0.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc

# IP: C:/Users/Shane/Documents/Classes/ECE_385/Lab_7/lab_7_ash/lab_7.srcs/sources_1/bd/mb_block/ip/mb_block_i_hdmi_text_controller_0_0/mb_block_i_hdmi_text_controller_0_0.xci
# IP: The module: 'mb_block_i_hdmi_text_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Shane/Documents/Classes/ECE_385/Lab_7/lab_7_ash/lab_7.gen/sources_1/bd/mb_block_i/ip/edit_hdmi_text_controller_v1_0.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: c:/Users/Shane/Documents/Classes/ECE_385/Lab_7/lab_7_ash/lab_7.gen/sources_1/bd/mb_block_i/ip/edit_hdmi_text_controller_v1_0.srcs/sources_1/ip/hdmi_tx_0/hdmi_tx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# XDC: c:/Users/Shane/Documents/Classes/ECE_385/Lab_7/lab_7_ash/lab_7.gen/sources_1/bd/mb_block_i/ip/edit_hdmi_text_controller_v1_0.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Shane/Documents/Classes/ECE_385/Lab_7/lab_7_ash/lab_7.gen/sources_1/bd/mb_block_i/ip/edit_hdmi_text_controller_v1_0.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
