# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pin_assignment/mb_usb_hdmi_top.xdc

# Block Designs: bd/mb_block/mb_block_i.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i || ORIG_REF_NAME==mb_block_i} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_i_microblaze_0_0/mb_block_i_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_microblaze_0_0 || ORIG_REF_NAME==mb_block_i_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_i_dlmb_v10_0/mb_block_i_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_dlmb_v10_0 || ORIG_REF_NAME==mb_block_i_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_i_ilmb_v10_0/mb_block_i_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_ilmb_v10_0 || ORIG_REF_NAME==mb_block_i_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_i_dlmb_bram_if_cntlr_0/mb_block_i_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_block_i_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_i_ilmb_bram_if_cntlr_0/mb_block_i_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_block_i_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_i_lmb_bram_0/mb_block_i_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_lmb_bram_0 || ORIG_REF_NAME==mb_block_i_lmb_bram_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_i_xbar_0/mb_block_i_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_xbar_0 || ORIG_REF_NAME==mb_block_i_xbar_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_i_microblaze_0_axi_periph_0/mb_block_i_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_block_i_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_i_microblaze_0_axi_intc_0/mb_block_i_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_block_i_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_i_mdm_1_0/mb_block_i_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_mdm_1_0 || ORIG_REF_NAME==mb_block_i_mdm_1_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_i_clk_wiz_1_0/mb_block_i_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_clk_wiz_1_0 || ORIG_REF_NAME==mb_block_i_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_i_rst_clk_wiz_1_100M_0/mb_block_i_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_block_i_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_i_axi_uartlite_0_0/mb_block_i_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_axi_uartlite_0_0 || ORIG_REF_NAME==mb_block_i_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_i_hdmi_text_controller_0_0/mb_block_i_hdmi_text_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_i_hdmi_text_controller_0_0 || ORIG_REF_NAME==mb_block_i_hdmi_text_controller_0_0} -quiet] -quiet

# XDC: c:/Users/Orion/Documents/GitHub/ece385/lab_7/lab_7.gen/sources_1/bd/mb_block_i/mb_block_i_ooc.xdc
